# Generated by Django 5.1.5 on 2025-02-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=255)),
                ('dep_description', models.TextField()),
                ('dep_image', models.ImageField(upload_to='dep_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_image', models.ImageField(upload_to='dep_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='Home.department')),
            ],
        ),
    ]
