# Generated by Django 5.1.5 on 2025-02-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doc_name',
            new_name='doctor_name',
        ),
    ]
