# Generated by Django 5.1.5 on 2025-02-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_rename_doctor_name_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dep_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='Home.department'),
        ),
    ]
